[package]
name = "imag-bookmark"
version = "0.6.4"
authors = ["Matthias Beyer <mail@beyermatthias.de>"]

description = "Part of the imag core distribution: imag-bookmark command"

keywords    = ["imag", "PIM", "personal", "information", "management"]
readme      = "../../../README.md"
license     = "LGPL-2.1"

documentation = "https://matthiasbeyer.github.io/imag/imag_documentation/index.html"
repository    = "https://github.com/matthiasbeyer/imag"
homepage      = "http://imag-pim.org"

[badges]
travis-ci                         = { repository = "matthiasbeyer/imag" }
is-it-maintained-issue-resolution = { repository = "matthiasbeyer/imag" }
is-it-maintained-open-issues      = { repository = "matthiasbeyer/imag" }
maintenance                       = { status     = "actively-developed" }

[dependencies]
clap = ">=2.17"
log = "0.4.0"
toml = "0.4"
toml-query = "0.6"

libimagrt        = { version = "0.6.4", path = "../../../lib/core/libimagrt" }
libimagerror     = { version = "0.6.4", path = "../../../lib/core/libimagerror" }
libimagbookmark  = { version = "0.6.4", path = "../../../lib/domain/libimagbookmark" }
libimagutil      = { version = "0.6.4", path = "../../../lib/etc/libimagutil" }
